<?php

function follow_custom_follow_networks_alter(&$networks, $uid = 0) {
    $networks[$uid]['imdb'] = array(
        'title' => t('IMDB'),
        'domain' => 'imdb.com',
    );

    $networks[$uid]['drupal'] = array(
        'title' => t('Drupal.org'),
        'domain' => 'drupal.org',
    );

    $networks[$uid]['github'] = array(
        'title' => t('Github'),
        'domain' => 'github.com',
    );


    drupal_add_css(drupal_get_path('module', 'follow_custom') .
        '/css/custom.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}
